service: geoip-serverless
frameworkVersion: ">=1.26.1 <2.0.0"

custom:
  stage: ${file(stages/${opt:stage, self:provider.stage}.yml)}
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

plugins:
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ${opt:region, self:custom.stage.region}
  profile: ${self:custom.stage.profile}
  memorySize: ${self:custom.stage.lambda.memorySize}
  timeout: ${self:custom.stage.lambda.timeout}
  iamRoleStatements: ${file(config/iamRoleStatements.yml)}
  deploymentBucket:
    name: com.serverless.${self:custom.stage.profile}.${self:provider.region}.deploys
  environment:
    ssmMaxmindToken: ${self:custom.stage.ssmMaxmindTokenName}
    locale: ${self:custom.stage.locale}
    dataBucket: ${self:custom.stage.dataBucket}
    dataPath: ${self:custom.stage.dataPath}

functions: ${file(lib/config.js):functions}
resources:
  Resources: ${file(lib/config.js):resources}
