# you can add statements to the Lambda function's IAM Role here
#  - Effect: "Allow"
#    Action:
#      - "s3:ListBucket"
#    Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#  - Effect: "Allow"
#    Action:
#      - "s3:PutObject"
#    Resource:
#      Fn::Join:
#        - ""
#        - - "arn:aws:s3:::"
#          - "Ref" : "ServerlessDeploymentBucket"
#          - "/*"
